FROM cgr.dev/chainguard/nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
# Certs are now dynamic and managed via portfolio_certs volume

# We will expose 8081 and 8443
EXPOSE 8081 8443

# The image already has the right entrypoint.
